title: Cedric Moeller
email: cedric.moeller@uni-hamburg.de
description: >-
  Passionate Ph.D. student specializing in knowledge graphs, with a strong background in knowledge extraction, entity linking, relation extraction, QA, and GNNs. Currently employed at the University of Hamburg.
baseurl: ""
url: ""
github_username:  cedricmoeller

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
