title: Cedric Moeller
email: cedric.moeller@uni-hamburg.de
description: >-
  I am a Ph.D. student focusing on knowledge graphs, with interests in knowledge extraction, entity linking, relation extraction, QA, and GNNs. Currently employed at the University of Hamburg.
baseurl: "/me"
url: "http:/cedricm.com"
github_username:  cedricmoeller

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
